### ISSUE TITLE
Cannot load MHA with HeaderSize=-1

### ISSUE THREAD

**Issue by aschuh-hf** [BioMedIA/deepali#148]
https://itk.org/Wiki/ITK/MetaIO/Documentation
> If these assumptions are false, the data will not be loaded correctly by the application. To fix these problems, MetaIO allows you to specify additional tag/value pairs in the header:
To skip the header bytes in the image data file, use
>
>    HeaderSize = X
>
> where X is the number of bytes to skip at the beginning of the file before reading image data. If you know there are no trailing bytes (extra bytes at the end of the file) you can specify
>
>    HeaderSize = -1
>
> and MetaImage will automatically calculate the number of extract bytes in the data file, assume they those bytes are at the head of the data file, and automatically skip them before beginning to read the image data.

**Comment by sgerber-hf** [comment]
Error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/deepali/data/image.py", line 1187, in read
    data, grid = read_image(path)
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/deepali/utils/imageio/__init__.py", line 26, in read_image
    return read_meta_image(path)
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/deepali/utils/imageio/meta.py", line 36, in read_meta_image
    data, meta = read_meta_image_from_fileobj(f)
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/deepali/utils/imageio/meta.py", line 272, in read_meta_image_from_fileobj
    f.seek((meta.get("HeaderSize") or 0), 1)
OverflowError: Python int too large to convert to C ssize_t
```

**Comment by sgerber-hf** [comment]
See [here](https://github.com/Kitware/MetaIO/blob/1a031fd8223c4846e2f90f50216cbcb415d52018/src/metaImage.cxx#L2604) for how ITK handles it

**Comment by aschuh-hf** [comment]
Perfect, thank you. The calculation of [readSize](https://github.com/Kitware/MetaIO/blob/1a031fd8223c4846e2f90f50216cbcb415d52018/src/metaImage.cxx#L2601) is good to have as a reference.

**Comment by sgerber-hf** [comment]
Implementation coming

**Comment by sgerber-hf** [comment]
See [pull request](https://github.com/BioMedIA/deepali/pull/149)
