### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by annareithmeir** [BioMedIA/deepali#55]
Thanks for this awesome repository!
If I want to reference it, which citation can I use?

**Comment by aschuh-hf** [comment]
Thanks for the kind words, Anna, and I appreciate you would like to give credits for using it!

My apologies for the late reply. One reason for this is that I didn't have a satisfactory answer to this. You may have noticed some recent changes, mostly to prepare some proper online documentation for this project and add some demos / tutorials for an event at Imperial College London. Aside from this, there is a plan to write up a technical report about this library which could be referenced. However, such citation does not currently exist and it will take some more time.

As a placeholder, I registered this project on Zenodo and added a [CITATION.cff](https://github.com/BioMedIA/deepali/blob/main/CITATION.cff) file with metadata which can be used to cite a specific release version of this software (e.g., [doi:10.5281/zenodo.8170162](https://doi.org/10.5281/zenodo.8170162)) for version 0.4.0 which I just published.
